
#jwt values
jwt_secret: oIhbd+QIyZnylJiHfnjjXcnHGXMicUqu9+no8qHAyXw=

#postgres config



spring:
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/askfm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.tawfeek.askme: DEBUG


server:
  port: 8080
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
# JPA settings
#spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.use-new-id-generator-mappings=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
#spring.jpa.properties.hibernate.connection.CharSet=utf-8
#spring.jpa.properties.hibernate.connection.useUnicode=true
